# Site settings
title: K
email: kiristrackgrose@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Follow me as I explore theories, themes, libraries, and products
  within the field of software engineering.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "kstrack-grose.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  kstrack-grose

# Build settings
markdown: kramdown
